name: credit-risk
channels:
  - conda-forge
  - defaults
dependencies:
  - brotlicffi=1.2.0.0=py311h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2025.11.12=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=py311hca03da5_0
  - expat=2.7.3=h50f4ffc_3
  - idna=3.11=py311hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_3
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_1
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py311hca03da5_1
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - urllib3=2.6.0=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - bcrypt==4.0.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - cryptography==46.0.3
      - dnspython==2.8.0
      - ecdsa==0.19.1
      - email-validator==2.3.0
      - fastapi==0.123.10
      - filelock==3.20.0
      - fsspec==2025.12.0
      - h11==0.16.0
      - httptools==0.7.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.6
      - numba==0.62.1
      - numpy==2.3.5
      - packaging==25.0
      - pandas==2.3.3
      - passlib==1.7.4
      - pyasn1==0.6.1
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pymongo==4.15.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-jose==3.5.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - shap==0.50.0
      - six==1.17.0
      - slicer==0.0.8
      - starlette==0.50.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.9.1
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0.1
prefix: /opt/miniconda3/envs/credit-risk
